### ISSUE TITLE
Increase column width for methodName field in MySQL log tables

### ISSUE THREAD

**Issue by egyedia** [metadatacenter/cedar-server-core-library#16]
The worker server throws this error in case the methodName is longer than 35 characters:

```
SQL Error: 1406, SQLState: 22001
Data truncation: Data too long for column 'methodName' at row 1
HHH000346: Error during managed flush [org.hibernate.exception.DataException: could not execute statement]
ERROR [2024-06-12 23:56:24,806] org.metadatacenter.worker.AppLoggerQueueProcessor: There was an error while handling the message
! com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'methodName' at row 1
! at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
! at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
! at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
! at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
! at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
! at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
! at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
! at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
! at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
! at java.base/java.lang.reflect.Method.invoke(Method.java:568)
! at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
! at jdk.proxy2/jdk.proxy2.$Proxy78.executeUpdate(Unknown Source)
! at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:175)
! ... 27 common frames omitted
! Causing: org.hibernate.exception.DataException: could not execute statement
! at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:52)
! at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
! at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
! at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
! at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:178)
! at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3185)
! at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3699)
! at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:90)
! at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:604)
! at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:478)
! at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:356)
! at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:39)
! at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1457)
! ... 19 common frames omitted
! Causing: javax.persistence.PersistenceException: org.hibernate.exception.DataException: could not execute statement
! at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
! at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
! at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:188)
! at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1463)
! at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:514)
! at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3321)
! at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2492)
! at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:473)
! at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:178)
! at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$300(JdbcResourceLocalTransactionCoordinatorImpl.java:39)
! at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:271)
! at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:104)
! at io.dropwizard.hibernate.UnitOfWorkAspect.commitTransaction(UnitOfWorkAspect.java:154)
! at io.dropwizard.hibernate.UnitOfWorkAspect.afterEnd(UnitOfWorkAspect.java:91)
! at io.dropwizard.hibernate.UnitOfWorkAwareProxyFactory.lambda$create$0(UnitOfWorkAwareProxyFactory.java:82)
! at org.metadatacenter.server.logging.AppLoggerExecutorService_$$_jvst20b_0.handleLog(AppLoggerExecutorService_$$_jvst20b_0.java)
! at org.metadatacenter.worker.AppLoggerQueueProcessor.digestMessages(AppLoggerQueueProcessor.java:52)
! at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
! at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
! at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
! at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
! at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
! at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by egyedia** [comment]
Was handled by this commit:
https://github.com/metadatacenter/cedar-microservice-libraries/commit/9d3973dbef569791bed0bec2a8a31ca478898500

When this will be deployed, the below SQL commands need to be executed:

```
ALTER TABLE cedar_log.log_cypher MODIFY COLUMN methodName VARCHAR(60);
ALTER TABLE cedar_log.log_request MODIFY COLUMN methodName VARCHAR(60);
```
